### ISSUE TITLE
`git://github.com/openembedded/meta-oe.git` does not exist anymore.

### ISSUE THREAD

**Issue by rubdos** [topic-embedded-products/meta-topic#2]
I'm working with Jan Helsen and trying to get the Yocto build working. The openembedded (manual) build works for now; I'm connected using `/dev/ttyUSB0`!

> A few recipes still require the "gitpkgv" class from meta-openembedded. Include it by cloning git://github.com/openembedded/meta-oe.git and add the path to its "meta-oe" subdirectory to the conf/bblayers.conf list. Getting rid of this meta-oe dependency is still on my TODO list.

I see this is on the `TODO` list; the repository `meta-oe` does not exist (anymore?). It seems to build here though.

**Comment by MikeLooijmans** [comment]
Fixed the link and removed the duplicate and confusing TODO remark

**Comment by rubdos** [comment]
Thank you.
